name: Bug Report
description: 报告 EnsoAI 的问题
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提交 Bug 报告！请填写以下信息以帮助我们定位问题。

  - type: input
    id: ensoai-version
    attributes:
      label: EnsoAI 版本号
      description: 可在应用设置或 `ensoai --version` 中查看
      placeholder: "例如: 0.2.27"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: 系统版本号
      description: 操作系统及版本
      placeholder: "例如: macOS 15.0 / Windows 11 23H2 / Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: 使用的 Shell
      description: 你使用的终端 shell
      placeholder: "例如: zsh / bash / fish / PowerShell"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 复现步骤
      description: 详细描述如何复现此问题
      placeholder: |
        1. 打开 EnsoAI
        2. 点击 ...
        3. 执行 ...
        4. 出现错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 你期望发生什么？
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么？
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: 如有相关错误日志，请粘贴在此
      render: shell
    validations:
      required: false
